### PR TITLE
Fixed json() from dict bug and added additional arguments on auth_ec2() method

### PR DESCRIPTION
**Pull request by sunghyun-lee**
This is for fixing #156.

### CODE REVIEW

**Comment by jeffwecan** [comment]
@sunghyun-lee: Apologies for the delay in getting a reply on this PR. If you're able to merge in the upstream branch and resolve the subsequent conflicts that have emerged we can get this merged in.

**Comment by jeffwecan** [comment]
On second thought, I went ahead and handled that merge conflict directly and will merge this in.

**Comment by sunghyun-lee** [comment]
Thanks!

**Comment by MJ111** [comment]
awesome dude!

**Pull request merged**
