### PR TITLE
Added support for /sys/generate-root endpoint 

### PR DESCRIPTION
**Pull request by bchannak**
The /sys/generate-root endpoint is used to create a new root key for Vault. Refer https://www.vaultproject.io/api/system/generate-root.html for more information.

### CODE REVIEW

**Comment by bchannak** [comment]
Hi,
I would need some help in addressing the issue I ran into when I raised this PR. This is the issue: https://travis-ci.org/ianunruh/hvac/jobs/279206024.

Thanks
-Bharath

**Comment by jamessoubry** [comment]
Hi @otakup0pe any progress on this PR? we need it to automate the initialisation of backends without admins having access to the existing root key

**Comment by otakup0pe** [comment]
Something funky with this build. Can you please make sure this branch is sync'd with the mainline ?

**Comment by bchannak** [comment]
Hi,
I have sync's with mainline and looks like all checks have passed. 

--Bharath

**Comment by jeffwecan** [comment]
Howdy @bchannak:

These changes look mostly fine to me. I'd like to see some tests included as well however. I proposed some integration tests on top of this branch in my fork and opened a PR to your fork/branch here: https://github.com/CiscoM31/hvac/pull/1. If you would like to merge in those proposed changes, or implement your own along those lines, I would be happy to get this PR merged. 👍

**Comment by jeffwecan** [comment]
To make sure we take advantage of these changes, I'm going to close out this PR and reopen it with the current master branch merged in (plus some test coverage).

**Comment by jeffwecan** [comment]
New PR that has been derived from this one: https://github.com/ianunruh/hvac/pull/199/files

**Pull request closed without merging**
