### PR TITLE
Fix handling of Vault redirects

### PR DESCRIPTION
**Pull request by willusher**
Code currently appends redirected URL to original server URL. 
e.g: https://vault:8200https://vault-host0/v1/sys/mounts

### CODE REVIEW

**Comment by ianunruh** [comment]
In my testing, the Vault server (v0.5.1) does not have an absolute URL in the Location header. Because of this, it is necessary to prepend the base URL to the relative URL provided from the Location header.

**Comment by tilgovi** [comment]
Maybe `urljoin` is a better alternative that would work no matter what?

https://docs.python.org/2/library/urlparse.html#urlparse.urljoin

**Comment by ianunruh** [comment]
@tilgovi thanks for the suggestion! I switched to `urljoin` in 327b73c33239ec0cb6df0b548e089096bcac9636

**Comment by tilgovi** [comment]
Cheers!

**Pull request closed without merging**
