### PR TITLE
Add method to reset previously-provided unseal keys

### PR DESCRIPTION
**Pull request by intgr**

### CODE REVIEW

**Comment by intgr** [comment]
Ping, any idea when you might have time to review or provide feedback?

**Comment by intgr** [comment]
@ianunruh Ping, do you still have time and energy to maintain this package? If not, maybe we should look for new maintainers.

**Comment by otakup0pe** [comment]
I can be a new maintainer 👼

**Comment by ianunruh** [comment]
@otakup0pe thanks for volunteering, I'll go ahead and add you to as a collaborator.

**Comment by intgr** [comment]
@otakup0pe Thank you! Are you also planning to make a release any time soon?

**Comment by otakup0pe** [comment]
As soon as I figure out how!

**Pull request merged**
