### PR TITLE
Add IAM auth

### PR DESCRIPTION
**Pull request by s3u**
This fixes #127. Thanks in advance for review/merge

### CODE REVIEW

**Comment by otakup0pe** [comment]
@s3u can you pull in from master? Tests should be working now!

**Comment by s3u** [comment]
Sorry, I missed this. Will do.

**Comment by s3u** [comment]
I submitted https://github.com/ianunruh/hvac/pull/155.

**Comment by mmahoney2U** [comment]
@s3u can you tell me (and possibly clarify in your documentation) what value would go into:

`vault_client.auth_iam(role)`

for "role"?

I've tried the full arn, which gives me the following error:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/hvac/v1/__init__.py", line 966, in auth_iam
    self._kwargs['verify'])
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/hvac/v1/__init__.py", line 970, in _authenticate_to_vault
    payload = self._generate_vault_request(role, vault_host)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/hvac/v1/__init__.py", line 1002, in _generate_vault_request
    request = client._endpoint.create_request(request_dict, operation_model)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/endpoint.py", line 152, in create_request
    operation_name=operation_model.name)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/signers.py", line 156, in sign
    auth.add_auth(request)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/auth.py", line 358, in add_auth
    canonical_request = self.canonical_request(request)
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/auth.py", line 300, in canonical_request
    cr.append(self.canonical_headers(headers_to_sign) + '\n')
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/auth.py", line 245, in canonical_headers
    sorted(headers_to_sign.get_all(key)))
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/auth.py", line 244, in <genexpr>
    value = ','.join(self._header_value(v) for v in
  File "/Users/mmahoney/src/honeycomb-playground/env/lib/python2.7/site-packages/botocore/auth.py", line 255, in _header_value
    return ' '.join(value.split())
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by Briansbum** [comment]
@mmahoney2U The role name goes there.

An arn like `arn:aws:iam::<my-role>:role/<my-role>` becomes `vault_client.auth_iam(<my-role>)`

**Pull request closed without merging**
