### PR TITLE
Add token role support

### LINKED ISSUE #63: Feature request: Token role support
The library does not yet support token roles (`/v1/auth/token/create/<role>` and family).

### PR DESCRIPTION
**Pull request by mfischer-zd**
Also, handle new types of errors thrown in Vault 0.6.

Closes #63

### CODE REVIEW

**Comment by ianunruh** [comment]
Hello! Thanks for the PR. Could you add an integration test for manipulating the token roles? Otherwise, everything else looks great.

**Comment by otakup0pe** [comment]
I did this but with tests https://github.com/ianunruh/hvac/pull/77

**Comment by ianunruh** [comment]
Closed in favor of #77

**Comment by ianunruh** [comment]
Oops, just noticed that this PRs don't actually overlap. This PR is for token roles, while #77 is for roles in AppRole auth.

**Comment by otakup0pe** [comment]
Oh snap my bad !

**Pull request closed without merging**
